name: PR
description: Default PR-template
title: CHANGES
body:
  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what this PR contains.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Related Issue
      description: >-
        #ISSUE_NUMBER
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: My changes generate no new warnings
        - label: My code builds and runs on my machine
        - label: I documented my code
  - type: textarea
    attributes:
      label: Screenshots/Screen recordings
      description: >-
        Please provide a screenshot, or preferred a screen recording
