name: Assign PR to creator

on:
  pull_request:
    types:
      - opened

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR to creator
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      - uses: actions/checkout@v3
      - name: Add pull request to Aurora Project Milestone 1
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/AuroraEditor/AuroraEditor/issues/${{ github.event.pull_request.number }}/assignees \
          -d '{"assignees":"${{ github.event.pull_request.user.login }}"}'
