name: Enable Automerge
on:
  pull_request:
    branches: [ main ]
jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"