name: Build
# & Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Swift (clean) Build
        run: set -o pipefail && xcodebuild -verbose -workspace "AuroraEditor.xcworkspace" -scheme "AuroraEditor" clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      #- name: Swift Test
      #  run: set -o pipefail && xcodebuild -verbose -workspace "AuroraEditor.xcworkspace" -scheme "AuroraEditorTests" clean test | xcpretty
