name: Auto approve
on: 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
          review-message: "[GitHub Action] - Approved GitHub PR for catching up main branch with development."
      - id: automerge
        name: Merge GitHub PR
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
